### ISSUE TITLE
Improve Shooting comfort

### ISSUE THREAD

**Issue by Alfadas** [Alfadas/LD46_AA-Jumper2#30]
further shooting improvements:

- [x] Fix Hit Feedback disappearing in Meshes
- [x] Change Hit Explosions to Fragmentations
- [x] New Bullet System
- [x] Change Muzzle from Vector3 to empty GameObject

**Comment by kruemelkeksfan** [comment]
Change Hit Feedback => Fix Hit Feedback disappearing in Meshes
